# Generated by Django 5.2.14 on 2026-05-26 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('sap', 'SAP (fuel & procurement)'), ('utility', 'Utility portal (electricity)'), ('travel', 'Corporate travel (Concur-style)')], max_length=20)),
                ('scope', models.CharField(choices=[('scope1', 'Scope 1 — direct'), ('scope2', 'Scope 2 — purchased energy'), ('scope3', 'Scope 3 — value chain')], max_length=10)),
                ('category', models.CharField(choices=[('fuel', 'Stationary/mobile fuel'), ('procurement', 'Purchased goods & services'), ('electricity', 'Purchased electricity'), ('flight', 'Business air travel'), ('hotel', 'Business lodging'), ('ground', 'Ground transport'), ('other', 'Other')], max_length=20)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('site_name', models.CharField(blank=True, max_length=255)),
                ('plant_code', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('unit_original', models.CharField(blank=True, max_length=32)),
                ('unit_normalized', models.CharField(blank=True, max_length=32)),
                ('quantity_normalized', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('origin', models.CharField(blank=True, max_length=64)),
                ('destination', models.CharField(blank=True, max_length=64)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('suspicion_reasons', models.JSONField(blank=True, default=list)),
                ('parse_warnings', models.JSONField(blank=True, default=list)),
                ('review_status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked for audit')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('source_reference', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-activity_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked'), ('edited', 'Edited by analyst')], max_length=20)),
                ('field_changes', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ingestion.activityrecord')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('sap', 'SAP (fuel & procurement)'), ('utility', 'Utility portal (electricity)'), ('travel', 'Corporate travel (Concur-style)')], max_length=20)),
                ('filename', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('rows_total', models.PositiveIntegerField(default=0)),
                ('rows_parsed', models.PositiveIntegerField(default=0)),
                ('rows_failed', models.PositiveIntegerField(default=0)),
                ('rows_suspicious', models.PositiveIntegerField(default=0)),
                ('error_summary', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_runs', to='ingestion.organization')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='ingestion_run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='ingestion.ingestionrun'),
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='ingestion.organization'),
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('raw_payload', models.JSONField()),
                ('parse_error', models.TextField(blank=True)),
                ('ingestion_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='ingestion.ingestionrun')),
            ],
            options={
                'ordering': ['row_number'],
                'unique_together': {('ingestion_run', 'row_number')},
            },
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='raw_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='ingestion.rawrecord'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='ingestion.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlantLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_code', models.CharField(max_length=20)),
                ('site_name', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='ingestion.organization')),
            ],
            options={
                'unique_together': {('organization', 'plant_code')},
            },
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['organization', 'review_status'], name='ingestion_a_organiz_fd7eb4_idx'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['organization', 'source_type'], name='ingestion_a_organiz_ca1c85_idx'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['organization', 'is_suspicious'], name='ingestion_a_organiz_013338_idx'),
        ),
    ]
